# Generated by Django 5.0.5 on 2024-05-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25, null=True, unique=True)),
                ("count", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Tags",
            },
        ),
    ]
