# Generated by Django 5.0.5 on 2024-05-07 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_posts", "0007_delete_repliestocomments"),
        ("service_users", "0005_alter_users_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="commentvotes",
            unique_together={("comment_id", "user_id", "is_upvote")},
        ),
    ]
