# Generated by Django 5.0.5 on 2024-05-06 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("service_answers", "0001_initial"),
        ("service_questions", "0001_initial"),
        ("service_users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answers",
            name="question_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="service_questions.questions",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="service_users.users"
            ),
        ),
    ]
