# Generated by Django 5.0.5 on 2024-05-07 02:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_answers", "0002_initial"),
        ("service_posts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answers",
            old_name="answer",
            new_name="body",
        ),
        migrations.AddField(
            model_name="answers",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="answers",
            name="downvote",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="answers",
            name="is_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="answers",
            name="is_favorite",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="answers",
            name="last_activity",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="answers",
            name="tags",
            field=models.ManyToManyField(to="service_posts.tags"),
        ),
        migrations.AddField(
            model_name="answers",
            name="upvote",
            field=models.IntegerField(default=0),
        ),
    ]
