# Generated by Django 5.0.5 on 2024-05-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "service_answers",
            "0003_rename_answer_answers_body_answers_created_at_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="answers",
            old_name="downvote",
            new_name="downvotes",
        ),
        migrations.RenameField(
            model_name="answers",
            old_name="upvote",
            new_name="favorite_count",
        ),
        migrations.RemoveField(
            model_name="answers",
            name="is_favorite",
        ),
        migrations.AddField(
            model_name="answers",
            name="upvotes",
            field=models.IntegerField(default=0),
        ),
    ]
