# Generated by Django 5.0.5 on 2024-05-10 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_users", "0005_alter_users_id"),
        ("service_votes", "0002_alter_uservotes_post_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="uservotes",
            unique_together={("user_id", "post_id", "post_type", "vote_type")},
        ),
    ]
