# Generated by Django 5.0.5 on 2024-05-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_votes", "0004_alter_uservotes_post_type_alter_uservotes_vote_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uservotes",
            name="post_type",
            field=models.CharField(
                choices=[("question", "Question"), ("answer", "Answer")], max_length=25
            ),
        ),
        migrations.AlterField(
            model_name="uservotes",
            name="vote_type",
            field=models.CharField(
                choices=[("upvote", "Upvote"), ("downvote", "Downvote")], max_length=25
            ),
        ),
    ]
