# Generated by Django 5.0.5 on 2024-05-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_votes", "0005_alter_uservotes_post_type_alter_uservotes_vote_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uservotes",
            name="post_id",
            field=models.IntegerField(blank=True),
        ),
    ]
