# Generated by Django 5.0.5 on 2024-05-06 21:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, db_index=True, max_length=55, unique=True
                    ),
                ),
                ("password", models.CharField(blank=True, max_length=255)),
                ("firstname", models.CharField(blank=True, max_length=25)),
                ("lastname", models.CharField(blank=True, max_length=25)),
                (
                    "displayname",
                    models.CharField(
                        blank=True, db_index=True, max_length=25, unique=True
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("websiteurl", models.URLField(blank=True, null=True)),
                (
                    "profileimage",
                    models.ImageField(blank=True, upload_to="./profile_images/"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Registered", "registed"), ("Anon", "anon")],
                        default="anon",
                        max_length=10,
                    ),
                ),
                ("is_employee", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Users",
            },
        ),
    ]
