# Generated by Django 5.0.5 on 2024-05-06 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="type",
        ),
    ]
