# Generated by Django 5.0.5 on 2024-05-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_users", "0002_remove_users_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
