# Generated by Django 5.0.5 on 2024-05-07 01:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_users", "0003_alter_users_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
