# Generated by Django 5.0.5 on 2024-05-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_users", "0004_alter_users_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
