# Generated by Django 5.0.5 on 2024-05-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_questions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questions",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="questions",
            name="last_activity",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
