# Generated by Django 5.0.5 on 2024-05-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_questions", "0002_alter_questions_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questions",
            name="downvote",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="questions",
            name="upvote",
            field=models.IntegerField(default=0),
        ),
    ]
