# Generated by Django 5.0.5 on 2024-05-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_questions", "0003_questions_downvote_questions_upvote"),
    ]

    operations = [
        migrations.RenameField(
            model_name="questions",
            old_name="downvote",
            new_name="downvotes",
        ),
        migrations.RenameField(
            model_name="questions",
            old_name="upvote",
            new_name="favorite_count",
        ),
        migrations.RenameField(
            model_name="questions",
            old_name="userid",
            new_name="user_id",
        ),
        migrations.RemoveField(
            model_name="questions",
            name="is_favorite",
        ),
        migrations.AddField(
            model_name="questions",
            name="upvotes",
            field=models.IntegerField(default=0),
        ),
    ]
