# Generated by Django 5.0.5 on 2024-05-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_questions", "0005_remove_questions_answer_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questions",
            name="last_activity",
            field=models.CharField(max_length=100),
        ),
    ]
