# Generated by Django 5.0.5 on 2024-05-09 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_questions", "0006_alter_questions_last_activity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="questions",
            old_name="user_id",
            new_name="owner",
        ),
        migrations.AlterField(
            model_name="questions",
            name="last_activity",
            field=models.CharField(
                blank=True,
                default=datetime.datetime(
                    2024, 5, 9, 18, 58, 50, 933414, tzinfo=datetime.timezone.utc
                ),
                max_length=100,
            ),
        ),
    ]
