# Generated by Django 5.0.5 on 2024-05-10 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "service_questions",
            "0008_questions_visibility_alter_questions_last_activity",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="questions",
            name="last_activity",
            field=models.CharField(
                blank=True,
                default=datetime.datetime(
                    2024, 5, 10, 18, 33, 55, 516202, tzinfo=datetime.timezone.utc
                ),
                max_length=100,
            ),
        ),
    ]
